import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { Header } from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";
import { UseSessionProvider } from "@/components/Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F0F4FA] min-h-screen`}>
        <UseSessionProvider>
          <Header />
          <main className="px-5">{children}</main>

          <Sidebar />

          <ToastContainer />
        </UseSessionProvider>
      </body>
    </html>
  );
}
